apiVersion: v1
kind: LimitRange

metadata:
  name: {{ include "app.fullname" . }}

spec:
  limits:
    - type: Container

      default:
        cpu: {{ .Values.limitRange.defaultCpuLimit | quote }}
        memory: {{ .Values.limitRange.defaultMemoryLimit | quote }}

      defaultRequest:
        cpu: {{ .Values.limitRange.defaultCpuRequest | quote }}
        memory: {{ .Values.limitRange.defaultMemoryRequest | quote }}