apiVersion: v1
kind: ResourceQuota

metadata:
  name: {{ include "app.fullname" . }}

spec:
  hard:
    requests.cpu: {{ .Values.resourceQuota.requestsCpu | quote }}
    requests.memory: {{ .Values.resourceQuota.requestsMemory | quote }}
    limits.cpu: {{ .Values.resourceQuota.limitsCpu | quote }}
    limits.memory: {{ .Values.resourceQuota.limitsMemory | quote }}
    pods: {{ .Values.resourceQuota.pods | quote }}