
#service#
service:
  port: 80
  targetPort: http


#ingress#
ingress:
  clusterIssuer: letsencrypt-prod
  className: nginx
  host: ramzans-lab.com

#cluster issuer#
certManager:
  
  clusterIssuer: letsencrypt-dev

  email: ramzankhan7871@gmail.com

  # Let's Encrypt production ACME server.
  # For development, use the staging URL instead.
  server: https://acme-v02.api.letsencrypt.org/directory #link to actual staging url for Let's Encrypt ACME server#

  # Secret where cert-manager stores the ACME account private key.
  privateKeySecret: letsencrypt-account-key

  # Optional with EKS Pod Identity because the region is supplied
  # through the Pod Identity environment. Keep it here if you want
  # the configuration to be explicit.
  region: eu-west-2 #change this to the one are route53 is in when we make it#

  # Your Route 53 hosted zone ID.
  hostedZoneID: YOUR_ROUTE53_HOSTED_ZONE_ID
#our actual route53 hosted zone id when we make it in aws#

#hpa#

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70


#pbd#

pdb:
  enabled: true
  minAvailable: 1


#resourceQuota#

resourceQuota:
  enabled: true

  requestsCpu: "2"

  requestsMemory: "2Gi"

  limitsCpu: "4"

  limitsMemory: "4Gi"

  pods: "20"


#LimitRange#

limitRange:
  enabled: true

  defaultCpuLimit: "500m"

  defaultMemoryLimit: "512Mi"

  defaultCpuRequest: "100m"

  defaultMemoryRequest: "128Mi"



#NetworkPolicy#

networkPolicy:
  enabled: true
  targetPort: http
