name: Terraform Plan Read Only

on:
  push:
    paths:
      - "terraform-plan-trigger.txt"

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-2
  AWS_ROLE_ARN: arn:aws:iam::557690622944:role/eks-v1-terraform-dev

jobs:
  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/envs/dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Plan
        run: terraform plan -input=false -no-color
